import type { Scheme } from "./types";

/**
 * Verified Initial Seed Dataset for Indian Government Credit Support & Subsidy Schemes.
 *
 * SOURCING INTEGRITY:
 * - Every scheme references active, official Government of India / State portals.
 * - Rules are structured and auditable (NO website scraping).
 * - Versioned with explicit last verification timestamps.
 */
export const SEED_GOVERNMENT_SCHEMES: Scheme[] = [
  {
    id: "9b1deb4d-3b7d-4bad-9bdd-2b0d7b3d0001",
    name: "Prime Minister's Employment Generation Programme (PMEGP)",
    slug: "pmegp",
    shortDescription:
      "Credit-linked subsidy program for setting up new micro-enterprises in manufacturing (up to ₹50L) and service sectors (up to ₹20L).",
    detailedDescription:
      "PMEGP is a flagship credit-linked subsidy programme administered by the Ministry of MSME through KVIC. It aims to generate continuous and sustainable employment opportunities in rural and urban areas by helping first-time entrepreneurs set up micro-enterprises with 15% to 35% margin money subsidy.",
    governmentLevel: "central",
    ministry: "Ministry of Micro, Small and Medium Enterprises (MSME)",
    category: "msme",
    purposes: [
      "business",
      "micro_enterprise",
      "manufacturing",
      "services",
      "startup",
      "self_employment",
      "working_capital",
      "machinery",
    ],
    beneficiaryTypes: ["individual", "first_time_entrepreneur", "shg", "cooperative", "trust"],
    benefits: [
      {
        type: "subsidy",
        summary: "15% to 35% margin money government subsidy based on location (rural/urban) and social category.",
        maxLoanAmount: 5_000_000,
        subsidyPercentage: 35,
        maxSubsidyAmount: 1_750_000,
        moratoriumMonths: 6,
      },
      {
        type: "composite_loan",
        summary: "Bank finance covers 60% to 75% of project cost, with beneficiary contribution between 5% and 10%.",
        maxLoanAmount: 5_000_000,
      },
    ],
    eligibilityRules: {
      combinator: "AND",
      rules: [
        {
          field: "age",
          operator: "greaterThanOrEqual",
          value: 18,
          isRequired: true,
          label: "Applicant must be at least 18 years of age.",
          category: "demographic",
        },
        {
          field: "loanPurpose",
          operator: "in",
          value: [
            "business",
            "micro_enterprise",
            "manufacturing",
            "services",
            "startup",
            "self_employment",
            "working_capital",
            "machinery",
            "unsecured",
            "secured",
          ],
          isRequired: true,
          label: "Financing must be for enterprise creation or business operations.",
          category: "enterprise",
        },
        {
          field: "loanAmount",
          operator: "lessThanOrEqual",
          value: 5_000_000,
          isRequired: true,
          label: "Project cost ceiling is up to ₹50 Lakh for manufacturing and ₹20 Lakh for services.",
          category: "financial",
        },
        {
          field: "businessStage",
          operator: "in",
          value: ["new", "expansion", "existing"],
          isRequired: false,
          label: "Primarily targets new greenfield micro-enterprises with select 2nd loan expansion options.",
          category: "enterprise",
        },
      ],
    },
    requiredDocuments: [
      "Aadhaar Card / Identity Proof",
      "Project Report / Business Plan",
      "Special Category Certificate (SC/ST/OBC/Minority/Women/Ex-Servicemen) if applicable",
      "Rural Area Certificate if applicable",
      "Educational Qualification Certificate (8th pass for projects above ₹10L in manufacturing / ₹5L in service)",
      "EDP (Entrepreneurship Development Programme) Training Certificate",
    ],
    officialSourceUrl: "https://www.kviconline.gov.in/pmegpep/pmegphome/index.jsp",
    applicationUrl: "https://www.kviconline.gov.in/pmegpep/pmegphome/index.jsp",
    sourceType: "ministry_portal",
    sourceName: "Khadi and Village Industries Commission (KVIC) / Ministry of MSME",
    version: "2026.1",
    effectiveFrom: "2008-08-15",
    lastVerifiedAt: "2026-09-15T00:00:00.000Z",
    active: true,
    priority: 10,
    metadata: {
      nodalAgency: "KVIC",
      implementingAgencies: ["KVIC", "KVIB", "DIC", "Coir Board"],
    },
  },
  {
    id: "9b1deb4d-3b7d-4bad-9bdd-2b0d7b3d0002",
    name: "Pradhan Mantri MUDRA Yojana (PMMY)",
    slug: "pmmy-mudra",
    shortDescription:
      "Collateral-free micro loans up to ₹10 Lakh (Shishu, Kishore, Tarun) for non-corporate, non-farm small and micro enterprises.",
    detailedDescription:
      "MUDRA provides collateral-free institutional refinance support to Member Lending Institutions (Banks, NBFCs, MFIs) for extending micro loans up to ₹10 Lakh to micro-enterprises engaged in manufacturing, trading, processing, and services.",
    governmentLevel: "central",
    ministry: "Department of Financial Services, Ministry of Finance",
    category: "msme",
    purposes: [
      "business",
      "micro_enterprise",
      "working_capital",
      "machinery",
      "trading",
      "services",
      "manufacturing",
      "self_employment",
      "unsecured",
    ],
    beneficiaryTypes: ["individual", "proprietorship", "partnership", "small_business_owner"],
    benefits: [
      {
        type: "collateral_free_loan",
        summary: "100% collateral-free loans across three tiers: Shishu (up to ₹50,000), Kishore (₹50k to ₹5L), and Tarun (₹5L to ₹10L).",
        maxLoanAmount: 1_000_000,
        collateralFreeLimit: 1_000_000,
      },
      {
        type: "credit_guarantee",
        summary: "Covered under Credit Guarantee Fund for Micro Units (CGFMU).",
      },
    ],
    eligibilityRules: {
      combinator: "AND",
      rules: [
        {
          field: "age",
          operator: "greaterThanOrEqual",
          value: 18,
          isRequired: true,
          label: "Applicant must be an Indian citizen of at least 18 years of age.",
          category: "demographic",
        },
        {
          field: "loanPurpose",
          operator: "in",
          value: [
            "business",
            "micro_enterprise",
            "working_capital",
            "machinery",
            "trading",
            "services",
            "manufacturing",
            "self_employment",
            "unsecured",
            "secured",
          ],
          isRequired: true,
          label: "Loan must be for non-farm income-generating business activities.",
          category: "enterprise",
        },
        {
          field: "loanAmount",
          operator: "lessThanOrEqual",
          value: 1_000_000,
          isRequired: true,
          label: "MUDRA standard product ceiling is ₹10 Lakh (Shishu: ≤₹50k, Kishore: ≤₹5L, Tarun: ≤₹10L).",
          category: "financial",
        },
      ],
    },
    requiredDocuments: [
      "Proof of Identity (Aadhaar, Voter ID, PAN, Driving Licence)",
      "Proof of Residence (Electricity bill, Ration card, Aadhaar)",
      "Applicant's Recent Passport Photos",
      "Quotation of Machinery / Items to be purchased",
      "Business Address Proof / Proof of Establishment",
      "Bank Account Statements for last 6 months",
    ],
    officialSourceUrl: "https://www.mudra.org.in/",
    applicationUrl: "https://www.udyamimitra.in/",
    sourceType: "ministry_portal",
    sourceName: "MUDRA / Department of Financial Services",
    version: "2026.1",
    effectiveFrom: "2015-04-08",
    lastVerifiedAt: "2026-09-15T00:00:00.000Z",
    active: true,
    priority: 9,
    metadata: {
      shishuLimit: 50_000,
      kishoreLimit: 500_000,
      tarunLimit: 1_000_000,
    },
  },
  {
    id: "9b1deb4d-3b7d-4bad-9bdd-2b0d7b3d0003",
    name: "Credit Guarantee Fund Trust for Micro and Small Enterprises (CGTMSE)",
    slug: "cgtmse",
    shortDescription:
      "Credit guarantee cover up to ₹5 Crore for collateral-free term loans and working capital to micro and small enterprises.",
    detailedDescription:
      "CGTMSE was set up jointly by the Ministry of MSME and SIDBI to provide credit guarantee coverage to Member Lending Institutions (MLIs), enabling commercial banks to extend credit without requiring third-party collateral or personal guarantees.",
    governmentLevel: "central",
    ministry: "Ministry of Micro, Small and Medium Enterprises (MSME) & SIDBI",
    category: "business",
    purposes: [
      "business",
      "msme",
      "micro_enterprise",
      "manufacturing",
      "services",
      "expansion",
      "working_capital",
      "machinery",
      "unsecured",
    ],
    beneficiaryTypes: ["msme", "proprietorship", "partnership", "pvt_ltd", "llp"],
    benefits: [
      {
        type: "credit_guarantee",
        summary: "75% to 85% credit guarantee cover to the lending institution for credit facilities up to ₹500 Lakh (₹5 Crore).",
        maxLoanAmount: 50_000_000,
        collateralFreeLimit: 50_000_000,
      },
    ],
    eligibilityRules: {
      combinator: "AND",
      rules: [
        {
          field: "loanPurpose",
          operator: "in",
          value: [
            "business",
            "msme",
            "micro_enterprise",
            "manufacturing",
            "services",
            "expansion",
            "working_capital",
            "machinery",
            "unsecured",
            "secured",
          ],
          isRequired: true,
          label: "Facility must be utilized for MSE manufacturing or service enterprise operations.",
          category: "enterprise",
        },
        {
          field: "loanAmount",
          operator: "lessThanOrEqual",
          value: 50_000_000,
          isRequired: true,
          label: "Maximum credit guarantee limit is ₹5 Crore per MSE borrower.",
          category: "financial",
        },
        {
          field: "hasCollateral",
          operator: "equals",
          value: false,
          isRequired: false,
          label: "Ideal pathway for enterprises seeking collateral-free institutional credit.",
          category: "financial",
        },
      ],
    },
    requiredDocuments: [
      "Udyam Registration Certificate",
      "Detailed Project Report (DPR) / Financial Forecasts",
      "ITR and Financial Statements for past 2-3 years (for existing enterprises)",
      "Bank Statement for past 6-12 months",
      "KYC documents of Promoters/Partners/Directors",
      "Copy of Lease / Ownership deed of factory / office premises",
    ],
    officialSourceUrl: "https://www.cgtmse.in/",
    applicationUrl: "https://www.cgtmse.in/",
    sourceType: "ministry_portal",
    sourceName: "Credit Guarantee Fund Trust for Micro and Small Enterprises (CGTMSE)",
    version: "2026.1",
    effectiveFrom: "2000-08-30",
    lastVerifiedAt: "2026-09-15T00:00:00.000Z",
    active: true,
    priority: 8,
    metadata: {
      guaranteeCoverPct: 85,
      maxLimitINR: 50_000_000,
    },
  },
  {
    id: "9b1deb4d-3b7d-4bad-9bdd-2b0d7b3d0004",
    name: "PM Vishwakarma Scheme",
    slug: "pm-vishwakarma",
    shortDescription:
      "End-to-end holistic support, skill certification, toolkit incentives, and collateral-free enterprise loans at 5% concessional interest rate for traditional artisans and craftspeople.",
    detailedDescription:
      "PM Vishwakarma provides comprehensive institutional recognition and credit support to traditional artisans and craftspersons across 18 notified trades (e.g. carpenters, blacksmiths, goldsmiths, potters, sculptors, cobblers, tailors, weavers). Features collateral-free enterprise credit of up to ₹3 Lakh (Tranche 1: ₹1L, Tranche 2: ₹2L) at a subsidized 5% interest rate.",
    governmentLevel: "central",
    ministry: "Ministry of Micro, Small and Medium Enterprises (MSME)",
    category: "artisan",
    purposes: [
      "artisan",
      "handicrafts",
      "business",
      "traditional_trade",
      "working_capital",
      "machinery",
      "self_employment",
    ],
    beneficiaryTypes: ["artisan", "craftsperson", "traditional_trade_worker", "individual"],
    benefits: [
      {
        type: "interest_subvention",
        summary: "Collateral-free enterprise credit up to ₹3 Lakh at a deeply concessional interest rate of 5% (with 8% interest subvention paid by MoMSME).",
        maxLoanAmount: 300_000,
        interestSubsidyPercentage: 8,
        collateralFreeLimit: 300_000,
        moratoriumMonths: 6,
      },
      {
        type: "skill_grant",
        summary: "₹15,000 modern toolkit grant + ₹500/day stipend during 5-7 days basic skill training + PM Vishwakarma Certificate & ID.",
      },
    ],
    eligibilityRules: {
      combinator: "AND",
      rules: [
        {
          field: "age",
          operator: "greaterThanOrEqual",
          value: 18,
          isRequired: true,
          label: "Applicant must be at least 18 years of age.",
          category: "demographic",
        },
        {
          field: "artisanStatus",
          operator: "equals",
          value: true,
          isRequired: true,
          label: "Applicant must be engaged in one of the 18 notified traditional trades on hands and tools basis.",
          category: "enterprise",
        },
        {
          field: "loanAmount",
          operator: "lessThanOrEqual",
          value: 300_000,
          isRequired: true,
          label: "Enterprise development credit limit is ₹1 Lakh in first tranche, up to ₹2 Lakh in second tranche.",
          category: "financial",
        },
      ],
    },
    requiredDocuments: [
      "Aadhaar Card",
      "Mobile number linked with Aadhaar",
      "Bank Account details / Passbook",
      "Ration Card / Family details (one member per family rule)",
      "Trade verification certificate by Gram Panchayat / Urban Local Body",
    ],
    officialSourceUrl: "https://pmvishwakarma.gov.in/",
    applicationUrl: "https://pmvishwakarma.gov.in/",
    sourceType: "ministry_portal",
    sourceName: "PM Vishwakarma Portal / Ministry of MSME",
    version: "2026.1",
    effectiveFrom: "2023-09-17",
    lastVerifiedAt: "2026-09-15T00:00:00.000Z",
    active: true,
    priority: 8,
    metadata: {
      notifiedTradesCount: 18,
      concessionalInterestPct: 5,
    },
  },
  {
    id: "9b1deb4d-3b7d-4bad-9bdd-2b0d7b3d0005",
    name: "Stand-Up India Scheme",
    slug: "stand-up-india",
    shortDescription:
      "Bank loans between ₹10 Lakh and ₹1 Crore for setting up greenfield enterprises by SC/ST and Women entrepreneurs.",
    detailedDescription:
      "Stand-Up India facilitates bank loans between ₹10 Lakh and ₹100 Lakh to at least one Scheduled Caste (SC) or Scheduled Tribe (ST) borrower and at least one woman borrower per bank branch for setting up a greenfield enterprise in manufacturing, services, agri-allied, or trading.",
    governmentLevel: "central",
    ministry: "Department of Financial Services, Ministry of Finance / SIDBI",
    category: "women_entrepreneur",
    purposes: [
      "business",
      "greenfield",
      "manufacturing",
      "services",
      "trading",
      "working_capital",
      "machinery",
      "startup",
    ],
    beneficiaryTypes: ["women_entrepreneur", "sc_st", "proprietorship", "pvt_ltd", "partnership"],
    benefits: [
      {
        type: "composite_loan",
        summary: "Composite loan (term loan and working capital) between ₹10 Lakh and ₹1 Crore covering up to 85% of project cost.",
        maxLoanAmount: 10_000_000,
        moratoriumMonths: 18,
      },
      {
        type: "credit_guarantee",
        summary: "Covered under Credit Guarantee Scheme for Stand-Up India (NCGTC).",
        collateralFreeLimit: 10_000_000,
      },
    ],
    eligibilityRules: {
      combinator: "AND",
      rules: [
        {
          field: "age",
          operator: "greaterThanOrEqual",
          value: 18,
          isRequired: true,
          label: "Applicant must be at least 18 years of age.",
          category: "demographic",
        },
        {
          field: "socialCategory",
          operator: "in",
          value: ["sc", "st", "women"],
          isRequired: false,
          label: "Scheme specifically targets SC, ST, and/or Women entrepreneurs (minimum 51% shareholding for non-individuals).",
          category: "demographic",
        },
        {
          field: "loanAmount",
          operator: "range",
          value: [1_000_000, 10_000_000],
          isRequired: true,
          label: "Loan facility range is from ₹10 Lakh up to ₹1 Crore.",
          category: "financial",
        },
        {
          field: "businessStage",
          operator: "in",
          value: ["new", "startup"],
          isRequired: false,
          label: "Must be a greenfield enterprise (first-time venture of the applicant in the designated sector).",
          category: "enterprise",
        },
      ],
    },
    requiredDocuments: [
      "Identity Proof (Aadhaar / Voter ID / Passport)",
      "Residence Proof",
      "Caste Certificate (for SC/ST category) if applicable",
      "Project Report & Technical Feasibility Report",
      "Proof of Business Address / Memorandum & Articles of Association",
      "Partnership Deed / Incorporation Certificate (minimum 51% SC/ST/Woman stake)",
      "Promoters' Net Worth Statements and ITR for past 2 years",
    ],
    officialSourceUrl: "https://www.standupmitra.in/",
    applicationUrl: "https://www.standupmitra.in/",
    sourceType: "ministry_portal",
    sourceName: "Stand-Up Mitra / SIDBI & DFS",
    version: "2026.1",
    effectiveFrom: "2016-04-05",
    lastVerifiedAt: "2026-09-15T00:00:00.000Z",
    active: true,
    priority: 8,
    metadata: {
      minLoanAmount: 1_000_000,
      maxLoanAmount: 10_000_000,
    },
  },
  {
    id: "9b1deb4d-3b7d-4bad-9bdd-2b0d7b3d0006",
    name: "Maharashtra Mukhyamantri Rojgar Nirmiti Karyakram (CMEGP)",
    slug: "maha-cmegp",
    shortDescription:
      "Maharashtra state credit-linked subsidy program providing 15% to 35% capital subsidy for new micro and small enterprises.",
    detailedDescription:
      "CMEGP is a state initiative by the Directorate of Industries, Government of Maharashtra, modeled to generate self-employment in Maharashtra. Offers project financing up to ₹50 Lakh for manufacturing and ₹20 Lakh for service/agri-allied units with state capital subsidy.",
    governmentLevel: "state",
    ministry: "Industries Department, Government of Maharashtra",
    state: "Maharashtra",
    category: "business",
    purposes: [
      "business",
      "micro_enterprise",
      "manufacturing",
      "services",
      "self_employment",
      "working_capital",
      "machinery",
    ],
    beneficiaryTypes: ["individual", "maharashtra_resident", "proprietorship", "partnership"],
    benefits: [
      {
        type: "subsidy",
        summary: "15% to 35% state capital subsidy on total project cost (General: 15% Urban / 25% Rural; Special category: 25% Urban / 35% Rural).",
        maxLoanAmount: 5_000_000,
        subsidyPercentage: 35,
        maxSubsidyAmount: 1_750_000,
      },
    ],
    eligibilityRules: {
      combinator: "AND",
      rules: [
        {
          field: "state",
          operator: "equals",
          value: "Maharashtra",
          isRequired: true,
          label: "Applicant must be a permanent resident / domicile of Maharashtra state.",
          category: "location",
        },
        {
          field: "age",
          operator: "range",
          value: [18, 45],
          isRequired: true,
          label: "Applicant age must be between 18 and 45 years (up to 50 years for SC/ST/Women/Ex-Servicemen).",
          category: "demographic",
        },
        {
          field: "loanPurpose",
          operator: "in",
          value: [
            "business",
            "micro_enterprise",
            "manufacturing",
            "services",
            "self_employment",
            "working_capital",
            "machinery",
            "unsecured",
            "secured",
          ],
          isRequired: true,
          label: "Proposed enterprise must be in manufacturing, service, or agro-based industrial activities.",
          category: "enterprise",
        },
        {
          field: "loanAmount",
          operator: "lessThanOrEqual",
          value: 5_000_000,
          isRequired: true,
          label: "Project cost ceiling is ₹50 Lakh for manufacturing and ₹20 Lakh for service sector.",
          category: "financial",
        },
      ],
    },
    requiredDocuments: [
      "Maharashtra Domicile Certificate",
      "Aadhaar Card & PAN Card",
      "Educational Qualification Certificate (minimum 7th / 10th pass depending on project size)",
      "Detailed Project Report (DPR)",
      "Caste / Category Certificate if claiming special category subsidy",
      "Certificate of EDP Training",
    ],
    officialSourceUrl: "https://maha-cmegp.gov.in/",
    applicationUrl: "https://maha-cmegp.gov.in/",
    sourceType: "ministry_portal",
    sourceName: "Directorate of Industries, Maharashtra",
    version: "2026.1",
    effectiveFrom: "2019-08-01",
    lastVerifiedAt: "2026-09-15T00:00:00.000Z",
    active: true,
    priority: 9,
    metadata: {
      state: "Maharashtra",
      manufacturingMaxINR: 5_000_000,
      serviceMaxINR: 2_000_000,
    },
  },
];
