import { ASSUMPTIONS, type Assumptions } from "@/lib/config";
import { pct, tf, type Lang } from "@/lib/i18n";
import type { RateTier } from "@/lib/pricing";

/**
 * Strings for the secondary pages: /fairness, /report and the breadcrumbs of /method.
 * Every language has exactly the same keys (enforced by `PagesStrings`).
 * Templates use {name} placeholders filled with `tf` from lib/i18n.
 */

export type DataSource = "synthetic" | "kaggle";

export interface PagesStrings {
  crumbs: { home: string; fairness: string; report: string; method: string };
  common: { na: string; illustrative: string; simulation: string };
  /** Names of the illustrative pricing tiers in lib/pricing.ts. */
  tiers: Record<RateTier["id"], string>;
  sources: Record<DataSource, string>;
  /** Localized versions of the data note in public/metrics.json (written by scripts/evaluate.ts). */
  dataNote: Record<DataSource, string>;
  fairness: {
    eyebrow: string;
    title: string;
    methodBody: string;
    tiles: {
      headline: string;
      headlineSub: string;
      age: string;
      income: string;
      bandSub: string;
      audited: string;
      auditedSub: string;
    };
    panels: { age: string; income: string; gap: string; caption: string };
    table: { group: string; rejected: string; effort: string; noPlan: string; months: string };
    chart: { aria: string; most: string; least: string; seriesName: string; value: string };
    /** Income band labels, rebuilt from the English labels in metrics.json. */
    groups: { under: string; range: string; plus: string };
    explain: {
      effortTitle: string;
      effortBody: string;
      compareTitle: string;
      compareBody: string;
      careTitle: string;
      careBody: string;
    };
    cta: { method: string; report: string };
  };
  report: {
    title: string;
    sub: string;
    applicant: string;
    decision: string;
    reasons: string;
    plan: string;
    timeline: string;
    assumptions: string;
    model: string;
    modelBody: string;
    rights: string;
    rightsBody: string;
    print: string;
    back: string;
    lender: string;
    ref: string;
    trained: string;
    points: string;
  };
  money: {
    title: string;
    titleApproved: string;
    loan: string;
    loanApproved: string;
    today: string;
    after: string;
    declined: string;
    alternative: string;
    tier: string;
    apr: string;
    emi: string;
    interest: string;
    perMonth: string;
    saved: string;
    emiDrop: string;
    noSaving: string;
    approvedBody: string;
    nextTier: string;
    topTier: string;
    note: string;
    declinedNote: string;
    tierItem: string;
  };
  certainty: {
    title: string;
    intro: string;
    likely: string;
    best: string;
    worst: string;
    monthN: string;
    beyond: string;
    share: string;
    none: string;
    axis: string;
    aria: string;
    note: string;
    percentile: string;
  };
  /** The plan assumptions from lib/config.ts, as label + value templates (see `assumptionItems`). */
  assumptions: Record<AssumptionKey, { label: string; value: string }>;
  method: { englishOnly: string };
}

export type AssumptionKey = "horizon" | "utilization" | "debt" | "income" | "lines" | "late" | "never";

export const PAGES: Record<Lang, PagesStrings> = {
  en: {
    crumbs: { home: "Home", fairness: "Fairness audit", report: "Lender report", method: "How it works" },
    common: { na: "n/a", illustrative: "Illustrative", simulation: "Simulation" },
    tiers: { excellent: "Excellent", "very-good": "Very good", good: "Good", fair: "Fair" },
    sources: { synthetic: "synthetic", kaggle: "Kaggle" },
    dataNote: {
      synthetic:
        "Synthetic dataset generated by ml/train.py with the same columns as Kaggle 'Give Me Some Credit' (data/cs-training.csv was not present); 25% stratified hold-out",
      kaggle: "Kaggle 'Give Me Some Credit' (cs-training.csv, 150,000 rows): 60% training, 20% validation, 20% test, stratified",
    },
    fairness: {
      eyebrow: "Fairness audit",
      title: "At the same risk, who has to work harder?",
      methodBody:
        "Rejected applicants are split into Pathway-score risk bands; each group's mean plan effort is directly standardized to the overall risk-band mix, so groups are compared at the same risk level.",
      tiles: {
        headline: "Headline effort gap",
        headlineSub: "{high} vs {low}",
        age: "Age gap",
        income: "Income gap",
        bandSub: "most vs least effort band",
        audited: "Rejected applicants audited",
        auditedSub: "{source} hold-out data",
      },
      panels: {
        age: "By age band",
        income: "By income band",
        gap: "{v} gap",
        caption:
          "Risk-adjusted mean plan effort per group, the share of rejected applicants with no feasible plan, and the median months to approval.",
      },
      table: { group: "Group", rejected: "Rejected", effort: "Adj. effort", noPlan: "No plan", months: "Median months" },
      chart: {
        aria: "Bar chart, {title}: risk-adjusted mean plan effort per group. {list}. Most effort: {most}. Least effort: {least}.",
        most: "most effort",
        least: "least effort",
        seriesName: "Risk-adjusted mean",
        value: "{v} effort (n={n})",
      },
      groups: { under: "Under {a} a month", range: "{a} to {b} a month", plus: "{a} or more a month" },
      explain: {
        effortTitle: "What “effort” means",
        effortBody:
          "The weighted size of the lowest-effort plan: {util} point per 10 points of card utilisation paid down, {debt} per 10% cut in EMIs, {lines} per active loan or card changed, {income} per 5% income growth, {wait} per month of waiting. Weights live in lib/config.ts.",
        compareTitle: "How groups are compared",
        compareBody:
          "Risk bands by Pathway score: {bands}. Each group's mean effort is re-weighted to the overall risk mix, so a gap is not just “this group is riskier”.",
        careTitle: "Read with care",
        careBody:
          "{note}. Age is never changed by a plan, but it is a model input, so it shapes how much other change is needed. That is exactly what this audit makes visible.",
      },
      cta: { method: "How the model and plans work", report: "Open a lender report" },
    },
    report: {
      title: "Statement of reasons for credit decision",
      sub: "Reasons in writing, as RBI's Fair Practices Code asks of lenders (simulated)",
      applicant: "Applicant data used",
      decision: "Decision",
      reasons: "Principal reasons, ranked",
      plan: "Path to approval",
      timeline: "Projected timeline",
      assumptions: "Assumptions",
      model: "Model",
      modelBody:
        "Logistic regression on {source} data (Give Me Some Credit schema), test AUC {auc} (validation AUC {validationAuc}). Reason codes are exact per-feature contributions to the log-odds, relative to the average applicant.",
      rights: "Your rights (illustrative)",
      rightsBody:
        "You may request a human review of this decision, correct any inaccurate data, and re-apply. This report explains the factors used; the model does not use age, dependents or real-estate loans.",
      print: "Print / save as PDF",
      back: "Back to applicant",
      lender: "Pathway · Demo Lender",
      ref: "Ref {ref}",
      trained: "Model trained {date}",
      points: "−{n} pts",
    },
    money: {
      title: "Money saved by following the plan",
      titleApproved: "Price of credit today",
      loan: "The same loan of {amount} over {months} months, priced today and after the plan.",
      loanApproved: "A loan of {amount} over {months} months at today's score.",
      today: "Today",
      after: "After the plan",
      declined: "Declined by a prime lender",
      alternative: "High-cost alternative",
      tier: "{tier} tier",
      apr: "{v} a year",
      emi: "Monthly payment (EMI)",
      interest: "Total interest",
      perMonth: "{v}/mo",
      saved: "Projected interest saved",
      emiDrop: "{v} lower monthly payment",
      noSaving:
        "The closest plan does not reach approval within {n} months, so the projected rate stays at the high-cost alternative.",
      approvedBody: "Already approved in the {tier} tier at {apr} a year. No plan needed.",
      nextTier: "The next tier, {tier} at {apr} a year, starts at score {score}.",
      topTier: "This is already the best illustrative tier.",
      note: "Illustrative risk-based pricing, not any lender's actual rates and not an offer of credit. Tiers: {tiers}.",
      declinedNote:
        "Below score {threshold} a prime lender declines, so the comparison uses a high-cost alternative at {alt} a year.",
      tierItem: "score {score}+ {apr}",
    },
    certainty: {
      title: "Timeline certainty",
      intro: "{runs} simulated futures of the same plan, each with its own pace and setbacks.",
      likely: "Likely approval",
      best: "Best case",
      worst: "Worst case",
      monthN: "month {n}",
      beyond: "beyond {n} months",
      share: "{share} of simulated futures reach approval within {n} months.",
      none: "Most simulated futures do not reach approval within {n} months.",
      axis: "Months from today",
      aria: "Approval month across simulated futures, on a scale of 0 to {n} months: best case {best}, likely {likely}, worst case {worst}.",
      note: "Each simulated future draws its own pace of paydown and income growth, and may include an income shock or a new late payment. Best and worst case are the {low} and {high} percentiles; likely is the median. A projection, not a promise.",
      percentile: "{n}th",
    },
    assumptions: {
      horizon: { label: "Plan horizon", value: "{n} months maximum" },
      utilization: { label: "Card paydown pace", value: "up to {v} points of card utilisation per month" },
      debt: { label: "EMI reduction", value: "{v} of today's EMIs per month, {max} max" },
      income: { label: "Income growth", value: "{v} per month, capped at +{max} in total" },
      lines: { label: "Active loans and cards", value: "change by at most {n}, effective after {lag} month" },
      late: {
        label: "Late payments",
        value: "counted over {n} months, assumed evenly spread, age out if every future payment is on time",
      },
      never: { label: "Not used by the model", value: "age, dependents, real-estate loans" },
    },
    method: { englishOnly: "This page is available in English only." },
  },
  hi: {
    crumbs: { home: "होम", fairness: "निष्पक्षता जाँच", report: "ऋणदाता रिपोर्ट", method: "यह कैसे काम करता है" },
    common: { na: "लागू नहीं", illustrative: "उदाहरण", simulation: "सिमुलेशन" },
    tiers: { excellent: "उत्कृष्ट", "very-good": "बहुत अच्छी", good: "अच्छी", fair: "सामान्य" },
    sources: { synthetic: "कृत्रिम", kaggle: "Kaggle" },
    dataNote: {
      synthetic:
        "ml/train.py द्वारा बनाया गया कृत्रिम डेटासेट, जिसमें Kaggle 'Give Me Some Credit' जैसे ही कॉलम हैं (data/cs-training.csv उपलब्ध नहीं था); 25% स्तरीकृत होल्ड-आउट",
      kaggle: "Kaggle 'Give Me Some Credit' (cs-training.csv, 150,000 पंक्तियाँ): 60% प्रशिक्षण, 20% वैलिडेशन, 20% टेस्ट, स्तरीकृत",
    },
    fairness: {
      eyebrow: "निष्पक्षता जाँच",
      title: "समान जोखिम पर, किसे ज़्यादा मेहनत करनी पड़ती है?",
      methodBody:
        "अस्वीकृत आवेदकों को पाथवे स्कोर के जोखिम-समूहों में बाँटा जाता है; हर समूह के औसत योजना-प्रयास को कुल जोखिम-मिश्रण के अनुसार मानकीकृत किया जाता है, ताकि सभी समूहों की तुलना समान जोखिम स्तर पर हो।",
      tiles: {
        headline: "मुख्य प्रयास अंतर",
        headlineSub: "{high} बनाम {low}",
        age: "आयु अंतर",
        income: "आय अंतर",
        bandSub: "सबसे ज़्यादा बनाम सबसे कम प्रयास वाला समूह",
        audited: "जाँचे गए अस्वीकृत आवेदक",
        auditedSub: "{source} होल्ड-आउट डेटा",
      },
      panels: {
        age: "आयु वर्ग के अनुसार",
        income: "आय वर्ग के अनुसार",
        gap: "{v} अंतर",
        caption:
          "हर समूह का जोखिम-समायोजित औसत योजना-प्रयास, बिना व्यावहारिक योजना वाले अस्वीकृत आवेदकों का हिस्सा, और स्वीकृति तक के मीडियन महीने।",
      },
      table: {
        group: "समूह",
        rejected: "अस्वीकृत",
        effort: "समायोजित प्रयास",
        noPlan: "कोई योजना नहीं",
        months: "मीडियन महीने",
      },
      chart: {
        aria: "बार चार्ट, {title}: हर समूह का जोखिम-समायोजित औसत योजना-प्रयास। {list}। सबसे ज़्यादा प्रयास: {most}। सबसे कम प्रयास: {least}।",
        most: "सबसे ज़्यादा प्रयास",
        least: "सबसे कम प्रयास",
        seriesName: "जोखिम-समायोजित औसत",
        value: "{v} प्रयास (n={n})",
      },
      groups: { under: "{a}/माह से कम", range: "{a} से {b}/माह", plus: "{a} या अधिक/माह" },
      explain: {
        effortTitle: "“प्रयास” का अर्थ",
        effortBody:
          "सबसे आसान योजना का भारित आकार: कार्ड उपयोग में हर 10 अंक की कमी पर {util} अंक, EMI में हर 10% कटौती पर {debt}, हर सक्रिय ऋण या कार्ड के बदलाव पर {lines}, आय में हर 5% वृद्धि पर {income}, और प्रतीक्षा के हर महीने पर {wait}। ये भार lib/config.ts में हैं।",
        compareTitle: "समूहों की तुलना कैसे होती है",
        compareBody:
          "पाथवे स्कोर के जोखिम-समूह: {bands}। हर समूह के औसत प्रयास को कुल जोखिम-मिश्रण के अनुसार दोबारा तौला जाता है, ताकि अंतर का मतलब सिर्फ़ “यह समूह ज़्यादा जोखिम वाला है” न हो।",
        careTitle: "सावधानी से पढ़ें",
        careBody:
          "{note}। योजना कभी आयु नहीं बदलती, लेकिन आयु मॉडल का एक इनपुट है, इसलिए यह तय करती है कि बाकी कितना बदलाव चाहिए। यही बात यह जाँच सामने लाती है।",
      },
      cta: { method: "मॉडल और योजनाएँ कैसे काम करती हैं", report: "ऋणदाता रिपोर्ट खोलें" },
    },
    report: {
      title: "ऋण निर्णय के कारणों का विवरण",
      sub: "लिखित कारण, जैसा RBI की उचित व्यवहार संहिता ऋणदाताओं से कहती है (सिमुलेशन)",
      applicant: "प्रयुक्त आवेदक डेटा",
      decision: "निर्णय",
      reasons: "मुख्य कारण, क्रम से",
      plan: "स्वीकृति का रास्ता",
      timeline: "अनुमानित समयरेखा",
      assumptions: "मान्यताएँ",
      model: "मॉडल",
      modelBody:
        "{source} डेटा पर लॉजिस्टिक रिग्रेशन (Give Me Some Credit स्कीमा), टेस्ट AUC {auc} (वैलिडेशन AUC {validationAuc})। कारण-कोड औसत आवेदक की तुलना में लॉग-ऑड्स में हर कारक का सटीक योगदान हैं।",
      rights: "आपके अधिकार (उदाहरण)",
      rightsBody:
        "आप इस निर्णय की मानवीय समीक्षा माँग सकते हैं, गलत डेटा सुधरवा सकते हैं और दोबारा आवेदन कर सकते हैं। यह रिपोर्ट प्रयुक्त कारकों को समझाती है; मॉडल आयु, आश्रितों या रियल-एस्टेट ऋणों का उपयोग नहीं करता।",
      print: "प्रिंट / PDF सहेजें",
      back: "आवेदक पर वापस",
      lender: "पाथवे · डेमो ऋणदाता",
      ref: "संदर्भ {ref}",
      trained: "मॉडल प्रशिक्षित {date}",
      points: "−{n} अंक",
    },
    money: {
      title: "योजना अपनाने से होने वाली बचत",
      titleApproved: "आज क्रेडिट की कीमत",
      loan: "{amount} का वही ऋण, {months} महीनों के लिए, आज की और योजना के बाद की दर पर।",
      loanApproved: "आज के स्कोर पर {months} महीनों के लिए {amount} का ऋण।",
      today: "आज",
      after: "योजना के बाद",
      declined: "मुख्य ऋणदाता द्वारा अस्वीकृत",
      alternative: "महँगा वैकल्पिक ऋण",
      tier: "{tier} श्रेणी",
      apr: "{v} सालाना",
      emi: "मासिक किस्त (EMI)",
      interest: "कुल ब्याज",
      perMonth: "{v}/माह",
      saved: "अनुमानित ब्याज बचत",
      emiDrop: "मासिक किस्त {v} कम",
      noSaving:
        "सबसे नज़दीकी योजना {n} महीनों में स्वीकृति तक नहीं पहुँचती, इसलिए अनुमानित दर महँगे विकल्प वाली ही रहती है।",
      approvedBody: "पहले से ही {tier} श्रेणी में {apr} सालाना ब्याज पर स्वीकृत। किसी योजना की ज़रूरत नहीं।",
      nextTier: "अगली श्रेणी, {tier} ({apr} सालाना ब्याज), स्कोर {score} से शुरू होती है।",
      topTier: "यह पहले से ही सबसे अच्छी उदाहरण-श्रेणी है।",
      note: "उदाहरण के लिए जोखिम-आधारित मूल्य निर्धारण: यह किसी ऋणदाता की वास्तविक दरें या ऋण का प्रस्ताव नहीं है। श्रेणियाँ: {tiers}।",
      declinedNote: "स्कोर {threshold} से नीचे मुख्य ऋणदाता अस्वीकार करता है, इसलिए तुलना {alt} सालाना ब्याज वाले महँगे विकल्प से की जाती है।",
      tierItem: "स्कोर {score}+ पर {apr}",
    },
    certainty: {
      title: "समयरेखा कितनी पक्की है",
      intro: "उसी योजना के {runs} सिम्युलेटेड भविष्य, हर एक की अपनी रफ़्तार और रुकावटों के साथ।",
      likely: "संभावित स्वीकृति",
      best: "सबसे अच्छी स्थिति",
      worst: "सबसे खराब स्थिति",
      monthN: "महीना {n}",
      beyond: "{n} महीनों के बाद",
      share: "{share} सिम्युलेटेड भविष्यों में {n} महीनों के भीतर स्वीकृति मिलती है।",
      none: "ज़्यादातर सिम्युलेटेड भविष्यों में {n} महीनों के भीतर स्वीकृति नहीं मिलती।",
      axis: "आज से महीने",
      aria: "सिम्युलेटेड भविष्यों में स्वीकृति का महीना, 0 से {n} महीनों के पैमाने पर: सबसे अच्छी स्थिति {best}, संभावित {likely}, सबसे खराब स्थिति {worst}।",
      note: "हर सिम्युलेटेड भविष्य में कर्ज़ चुकाने और आय बढ़ने की रफ़्तार अलग होती है, और उसमें आय का झटका या नया देर वाला भुगतान भी आ सकता है। सबसे अच्छी और सबसे खराब स्थिति क्रमशः {low} और {high} प्रतिशतक हैं; संभावित स्थिति मीडियन है। यह अनुमान है, वादा नहीं।",
      percentile: "{n}वाँ",
    },
    assumptions: {
      horizon: { label: "योजना की अवधि", value: "अधिकतम {n} महीने" },
      utilization: { label: "कार्ड बकाया घटाने की रफ़्तार", value: "हर महीने उपयोग में अधिकतम {v} अंक की कमी" },
      debt: { label: "EMI में कटौती", value: "हर महीने आज की EMI का {v}, अधिकतम {max}" },
      income: { label: "आय वृद्धि", value: "हर महीने {v}, कुल मिलाकर अधिकतम +{max}" },
      lines: { label: "सक्रिय ऋण और कार्ड", value: "अधिकतम {n} का बदलाव, {lag} महीने बाद लागू" },
      late: {
        label: "देर से भुगतान",
        value: "{n} महीनों में गिने जाते हैं, समान रूप से फैले माने जाते हैं, और आगे हर भुगतान समय पर हो तो रिकॉर्ड से हट जाते हैं",
      },
      never: { label: "मॉडल में उपयोग नहीं होता", value: "आयु, आश्रित, रियल-एस्टेट ऋण" },
    },
    method: { englishOnly: "यह पृष्ठ अभी केवल अंग्रेज़ी में उपलब्ध है।" },
  },
  mr: {
    crumbs: { home: "मुख्यपृष्ठ", fairness: "निष्पक्षता तपासणी", report: "कर्जदाता अहवाल", method: "हे कसे चालते" },
    common: { na: "लागू नाही", illustrative: "उदाहरणार्थ", simulation: "सिम्युलेशन" },
    tiers: { excellent: "उत्कृष्ट", "very-good": "खूप चांगली", good: "चांगली", fair: "साधारण" },
    sources: { synthetic: "कृत्रिम", kaggle: "Kaggle" },
    dataNote: {
      synthetic:
        "ml/train.py ने तयार केलेला कृत्रिम डेटासेट, ज्यात Kaggle 'Give Me Some Credit' सारखेच कॉलम आहेत (data/cs-training.csv उपलब्ध नव्हता); 25% स्तरित होल्ड-आउट",
      kaggle: "Kaggle 'Give Me Some Credit' (cs-training.csv, 150,000 ओळी): 60% प्रशिक्षण, 20% व्हॅलिडेशन, 20% टेस्ट, स्तरित",
    },
    fairness: {
      eyebrow: "निष्पक्षता तपासणी",
      title: "समान जोखमीवर, कोणाला जास्त मेहनत करावी लागते?",
      methodBody:
        "नामंजूर अर्जदारांना पाथवे स्कोअरच्या जोखीम-गटांमध्ये विभागले जाते; प्रत्येक गटाचा सरासरी योजना-प्रयत्न एकूण जोखीम-मिश्रणानुसार प्रमाणित केला जातो, जेणेकरून सर्व गटांची तुलना समान जोखमीच्या पातळीवर होते.",
      tiles: {
        headline: "मुख्य प्रयत्न तफावत",
        headlineSub: "{high} विरुद्ध {low}",
        age: "वय तफावत",
        income: "उत्पन्न तफावत",
        bandSub: "सर्वाधिक विरुद्ध सर्वात कमी प्रयत्नाचा गट",
        audited: "तपासलेले नामंजूर अर्जदार",
        auditedSub: "{source} होल्ड-आउट डेटा",
      },
      panels: {
        age: "वयोगटानुसार",
        income: "उत्पन्न गटानुसार",
        gap: "{v} तफावत",
        caption:
          "प्रत्येक गटाचा जोखीम-समायोजित सरासरी योजना-प्रयत्न, व्यवहार्य योजना नसलेल्या नामंजूर अर्जदारांचा वाटा, आणि मंजुरीपर्यंतचे मीडियन महिने.",
      },
      table: {
        group: "गट",
        rejected: "नामंजूर",
        effort: "समायोजित प्रयत्न",
        noPlan: "योजना नाही",
        months: "मीडियन महिने",
      },
      chart: {
        aria: "बार चार्ट, {title}: प्रत्येक गटाचा जोखीम-समायोजित सरासरी योजना-प्रयत्न. {list}. सर्वाधिक प्रयत्न: {most}. सर्वात कमी प्रयत्न: {least}.",
        most: "सर्वाधिक प्रयत्न",
        least: "सर्वात कमी प्रयत्न",
        seriesName: "जोखीम-समायोजित सरासरी",
        value: "{v} प्रयत्न (n={n})",
      },
      groups: { under: "{a}/महिन्यापेक्षा कमी", range: "{a} ते {b}/महिना", plus: "{a} किंवा अधिक/महिना" },
      explain: {
        effortTitle: "“प्रयत्न” म्हणजे काय",
        effortBody:
          "सर्वात सोप्या योजनेचा भारित आकार: कार्ड वापरात प्रत्येक 10 गुणांच्या घटीसाठी {util} गुण, EMI मध्ये प्रत्येक 10% कपातीसाठी {debt}, प्रत्येक सक्रिय कर्ज किंवा कार्डच्या बदलासाठी {lines}, उत्पन्नात प्रत्येक 5% वाढीसाठी {income}, आणि प्रतीक्षेच्या प्रत्येक महिन्यासाठी {wait}. हे भार lib/config.ts मध्ये आहेत.",
        compareTitle: "गटांची तुलना कशी होते",
        compareBody:
          "पाथवे स्कोअरनुसार जोखीम-गट: {bands}. प्रत्येक गटाचा सरासरी प्रयत्न एकूण जोखीम-मिश्रणानुसार पुन्हा तोलला जातो, जेणेकरून तफावत म्हणजे फक्त “हा गट जास्त जोखमीचा आहे” असे होत नाही.",
        careTitle: "काळजीपूर्वक वाचा",
        careBody:
          "{note}. योजना कधीही वय बदलत नाही, पण वय हे मॉडेलचे एक इनपुट आहे, त्यामुळे इतर किती बदल लागतील हे त्यावर ठरते. नेमके हेच ही तपासणी दाखवते.",
      },
      cta: { method: "मॉडेल आणि योजना कशा चालतात", report: "कर्जदाता अहवाल उघडा" },
    },
    report: {
      title: "कर्ज निर्णयाच्या कारणांचे विवरण",
      sub: "लेखी कारणे, जशी RBI ची उचित व्यवहार संहिता कर्जदात्यांना सांगते (सिम्युलेशन)",
      applicant: "वापरलेला अर्जदार डेटा",
      decision: "निर्णय",
      reasons: "मुख्य कारणे, क्रमाने",
      plan: "मंजुरीचा मार्ग",
      timeline: "अंदाजित वेळापत्रक",
      assumptions: "गृहितके",
      model: "मॉडेल",
      modelBody:
        "{source} डेटावर लॉजिस्टिक रिग्रेशन (Give Me Some Credit स्कीमा), टेस्ट AUC {auc} (व्हॅलिडेशन AUC {validationAuc}). कारण-कोड हे सरासरी अर्जदाराच्या तुलनेत लॉग-ऑड्समधील प्रत्येक घटकाचे अचूक योगदान आहेत.",
      rights: "तुमचे अधिकार (उदाहरणार्थ)",
      rightsBody:
        "तुम्ही या निर्णयाचे मानवी पुनरावलोकन मागू शकता, चुकीचा डेटा दुरुस्त करू शकता आणि पुन्हा अर्ज करू शकता. हा अहवाल वापरलेले घटक स्पष्ट करतो; मॉडेल वय, अवलंबित किंवा स्थावर मालमत्ता कर्जे वापरत नाही.",
      print: "प्रिंट / PDF जतन करा",
      back: "अर्जदाराकडे परत",
      lender: "पाथवे · डेमो कर्जदाता",
      ref: "संदर्भ {ref}",
      trained: "मॉडेल प्रशिक्षित {date}",
      points: "−{n} गुण",
    },
    money: {
      title: "योजना पाळल्याने होणारी बचत",
      titleApproved: "आज कर्जाची किंमत",
      loan: "{amount} चे तेच कर्ज, {months} महिन्यांसाठी, आजच्या आणि योजनेनंतरच्या दराने.",
      loanApproved: "आजच्या स्कोअरवर {months} महिन्यांसाठी {amount} चे कर्ज.",
      today: "आज",
      after: "योजनेनंतर",
      declined: "मुख्य कर्जदात्याकडून नामंजूर",
      alternative: "महागडा पर्यायी कर्जदाता",
      tier: "{tier} श्रेणी",
      apr: "{v} वार्षिक",
      emi: "मासिक हप्ता (EMI)",
      interest: "एकूण व्याज",
      perMonth: "{v}/महिना",
      saved: "अंदाजित व्याज बचत",
      emiDrop: "मासिक हप्ता {v} ने कमी",
      noSaving:
        "सर्वात जवळची योजना {n} महिन्यांत मंजुरीपर्यंत पोहोचत नाही, म्हणून अंदाजित दर महागड्या पर्यायाचाच राहतो.",
      approvedBody: "आधीच {tier} श्रेणीत {apr} वार्षिक व्याज वर मंजूर. कोणत्याही योजनेची गरज नाही.",
      nextTier: "पुढील श्रेणी, {tier} ({apr} वार्षिक व्याज), स्कोअर {score} पासून सुरू होते.",
      topTier: "ही आधीच सर्वोत्तम उदाहरण-श्रेणी आहे.",
      note: "उदाहरणादाखल जोखीम-आधारित किंमत: हे कोणत्याही कर्जदात्याचे प्रत्यक्ष दर किंवा कर्जाचा प्रस्ताव नाही. श्रेण्या: {tiers}.",
      declinedNote: "स्कोअर {threshold} खाली मुख्य कर्जदाता नामंजूर करतो, म्हणून तुलना {alt} वार्षिक व्याज असलेल्या महागड्या पर्यायाशी केली जाते.",
      tierItem: "स्कोअर {score}+ वर {apr}",
    },
    certainty: {
      title: "वेळापत्रक किती खात्रीशीर आहे",
      intro: "त्याच योजनेची {runs} सिम्युलेटेड भविष्ये, प्रत्येकाची स्वतःची गती आणि अडथळे.",
      likely: "संभाव्य मंजुरी",
      best: "सर्वोत्तम स्थिती",
      worst: "सर्वात वाईट स्थिती",
      monthN: "महिना {n}",
      beyond: "{n} महिन्यांनंतर",
      share: "{share} सिम्युलेटेड भविष्यांमध्ये {n} महिन्यांत मंजुरी मिळते.",
      none: "बहुतेक सिम्युलेटेड भविष्यांमध्ये {n} महिन्यांत मंजुरी मिळत नाही.",
      axis: "आजपासून महिने",
      aria: "सिम्युलेटेड भविष्यांतील मंजुरीचा महिना, 0 ते {n} महिन्यांच्या प्रमाणावर: सर्वोत्तम स्थिती {best}, संभाव्य {likely}, सर्वात वाईट स्थिती {worst}.",
      note: "प्रत्येक सिम्युलेटेड भविष्यात कर्जफेड आणि उत्पन्नवाढीची गती वेगळी असते, आणि त्यात उत्पन्नाचा धक्का किंवा नवीन उशिराचा हप्ता येऊ शकतो. सर्वोत्तम आणि सर्वात वाईट स्थिती अनुक्रमे {low} आणि {high} पर्सेंटाइल आहेत; संभाव्य स्थिती मीडियन आहे. हा अंदाज आहे, वचन नाही.",
      percentile: "{n}वे",
    },
    assumptions: {
      horizon: { label: "योजनेचा कालावधी", value: "जास्तीत जास्त {n} महिने" },
      utilization: { label: "कार्ड थकबाकी कमी करण्याची गती", value: "दरमहा वापरात जास्तीत जास्त {v} गुणांची घट" },
      debt: { label: "EMI मधील कपात", value: "दरमहा आजच्या EMI च्या {v}, जास्तीत जास्त {max}" },
      income: { label: "उत्पन्नवाढ", value: "दरमहा {v}, एकूण जास्तीत जास्त +{max}" },
      lines: { label: "सक्रिय कर्जे आणि कार्ड", value: "जास्तीत जास्त {n} ने बदल, {lag} महिन्यानंतर लागू" },
      late: {
        label: "उशिराचे हप्ते",
        value: "{n} महिन्यांत मोजले जातात, समान विखुरलेले मानले जातात, आणि पुढील प्रत्येक हप्ता वेळेवर भरल्यास नोंदीतून हटतात",
      },
      never: { label: "मॉडेलमध्ये वापरले जात नाही", value: "वय, अवलंबित, स्थावर मालमत्ता कर्जे" },
    },
    method: { englishOnly: "हे पान सध्या फक्त इंग्रजीत उपलब्ध आहे." },
  },
};

export const pagesText = (lang: Lang): PagesStrings => PAGES[lang];

/** Adds `?lang=` to an internal href (English is the default and keeps clean URLs). */
export function hrefWithLang(href: string, lang: Lang): string {
  if (lang === "en") return href;
  const [base, query = ""] = href.split("?");
  const q = new URLSearchParams(query);
  q.set("lang", lang);
  return `${base}?${q.toString()}`;
}

/** Narrows metrics.json's `dataSource` string. */
export const asDataSource = (v: string): DataSource => (v === "kaggle" ? "kaggle" : "synthetic");

/**
 * Localizes the income band labels written by the evaluator (lib/evaluate.ts INCOME_BANDS):
 * "Under ₹60,000/mo", "₹60,000 to ₹1.2 lakh/mo", "₹1.2 lakh+/mo". Amounts keep their digits; "lakh"
 * is translated.
 */
export function groupLabel(lang: Lang, label: string): string {
  const g = PAGES[lang].fairness.groups;
  const amount = (a: string) => a.replace(/ lakh$/, lang === "en" ? " lakh" : " लाख");
  let m = /^Under (₹[\d.,]+(?: lakh)?)\/mo$/.exec(label);
  if (m) return tf(g.under, { a: amount(m[1]) });
  m = /^(₹[\d.,]+(?: lakh)?) to (₹[\d.,]+(?: lakh)?)\/mo$/.exec(label);
  if (m) return tf(g.range, { a: amount(m[1]), b: amount(m[2]) });
  m = /^(₹[\d.,]+(?: lakh)?)\+\/mo$/.exec(label);
  if (m) return tf(g.plus, { a: amount(m[1]) });
  return label;
}

/** APR as a short percentage: 0.105 → "10.5%", 0.18 → "18%". */
export const aprText = (apr: number): string => `${(apr * 100).toFixed(1).replace(/\.0$/, "")}%`;

/** A ratio like 1.3096 as the gap it represents: "31.0%". */
export const gapText = (ratio: number): string => `${((ratio - 1) * 100).toFixed(1)}%`;

/** The plan assumptions in lib/config.ts as localized label/value pairs (English matches describeAssumptions()). */
export function assumptionItems(lang: Lang, a: Assumptions = ASSUMPTIONS): { key: AssumptionKey; label: string; value: string }[] {
  const s = PAGES[lang].assumptions;
  const values: Record<AssumptionKey, Record<string, string | number>> = {
    horizon: { n: a.horizonMonths },
    utilization: { v: pct(a.utilizationPaydownPerMonth) },
    debt: { v: pct(a.debtPaymentCutPerMonth), max: pct(a.maxDebtPaymentCut) },
    income: { v: pct(a.incomeGrowthPerMonth, 1), max: pct(a.maxIncomeGrowth) },
    lines: { n: a.maxOpenLineChange, lag: a.openLineLagMonths },
    late: { n: a.delinquencyWindowMonths },
    never: {},
  };
  return (Object.keys(values) as AssumptionKey[]).map((key) => ({
    key,
    label: s[key].label,
    value: tf(s[key].value, values[key]),
  }));
}
