import type { Lang } from "../i18n";

/**
 * Strings for the answer hero, the score breakdown and the what-if sliders, in English, Hindi and
 * Marathi. The English object defines the shape; the other languages must match it key for key.
 */
const en = {
  hero: {
    kicker: "Your answer",
    declinedAt: "You are at {score}.",
    approvedAt: "You are approved at {score}.",
    away: "{n} points from approval.",
    aboutRange: "About {when}, most likely {low} to {high} months.",
    about: "About {when}.",
    noPlan: "No plan we can model gets you approved within {n} months.",
    nextTier: "The next rate tier is {n} points away.",
    bestTier: "You are already in the best rate tier.",
    foot: "Score and timing come from the credit model and a simulation of your plan.",
  },
  breakdown: {
    kicker: "Inside the score",
    title: "What lifts your score and what pulls it down",
    sub: "Every input the model reads, in score points, compared with an average applicant.",
    lifts: "Lifts your score",
    pulls: "Pulls it down",
    pts: "points",
    nothingLifts: "Nothing lifts your score above average yet.",
    nothingPulls: "Nothing pulls your score below average.",
    note: "Points are exact contributions from the model, not estimates.",
  },
  whatIf: {
    kicker: "What if",
    title: "Try a change and watch the score move",
    sub: "Move the sliders. The same model scores the new numbers instantly. Nothing is saved.",
    sliders: "Your numbers",
    utilization: "Card utilization",
    debtRatio: "Debt ratio (EMIs over income)",
    incomeGrowth: "Income raise",
    openCreditLines: "Open loans and cards",
    monthsWaited: "Months of on-time payments",
    today: "Today: {value}",
    incomeUnusable: "Income was not provided, so a raise cannot change the score.",
    monthsHint: "Late payments older than 24 months drop off.",
    result: "New result",
    newScore: "New score",
    change: "Change",
    pts: "points",
    pt: "point",
    decision: "Decision",
    approved: "Approved",
    declined: "Declined",
    toApproval: "Points to approval",
    reached: "Reached",
    apr: "Yearly rate",
    noApr: "No prime offer",
    emi: "Monthly EMI",
    interestSaved: "Interest saved",
    noSaving: "No saving yet",
    loanNote: "On {amount} over {term} months. Rates are illustrative.",
    reset: "Reset",
    apply: "Use these numbers",
  },
};

type Strings = typeof en;

const hi: Strings = {
  hero: {
    kicker: "आपका जवाब",
    declinedAt: "आप {score} पर हैं।",
    approvedAt: "आप {score} पर स्वीकृत हैं।",
    away: "स्वीकृति से {n} अंक दूर।",
    aboutRange: "लगभग {when}, सबसे संभावित {low} से {high} महीने।",
    about: "लगभग {when}।",
    noPlan: "हमारे मॉडल की किसी योजना से {n} महीनों में स्वीकृति नहीं मिलती।",
    nextTier: "अगला दर स्तर {n} अंक दूर है।",
    bestTier: "आप पहले से सबसे अच्छे दर स्तर में हैं।",
    foot: "स्कोर और समय क्रेडिट मॉडल और आपकी योजना के सिमुलेशन से आते हैं।",
  },
  breakdown: {
    kicker: "स्कोर के अंदर",
    title: "क्या स्कोर बढ़ाता है और क्या घटाता है",
    sub: "मॉडल जो भी जानकारी पढ़ता है, औसत आवेदक की तुलना में अंकों में।",
    lifts: "स्कोर बढ़ाता है",
    pulls: "स्कोर घटाता है",
    pts: "अंक",
    nothingLifts: "अभी कुछ भी स्कोर को औसत से ऊपर नहीं ले जा रहा।",
    nothingPulls: "कुछ भी स्कोर को औसत से नीचे नहीं ले जा रहा।",
    note: "अंक मॉडल के सटीक योगदान हैं, अनुमान नहीं।",
  },
  whatIf: {
    kicker: "अगर ऐसा हो",
    title: "बदलाव आज़माएँ और स्कोर को हिलते देखें",
    sub: "स्लाइडर हिलाएँ। वही मॉडल नए आँकड़ों को तुरंत स्कोर करता है। कुछ भी सहेजा नहीं जाता।",
    sliders: "आपके आँकड़े",
    utilization: "कार्ड उपयोग",
    debtRatio: "ऋण अनुपात (आय के मुकाबले EMI)",
    incomeGrowth: "आय में बढ़ोतरी",
    openCreditLines: "चालू ऋण और कार्ड",
    monthsWaited: "समय पर भुगतान के महीने",
    today: "आज: {value}",
    incomeUnusable: "आय नहीं दी गई, इसलिए बढ़ोतरी से स्कोर नहीं बदलेगा।",
    monthsHint: "24 महीने से पुराने देर के भुगतान हट जाते हैं।",
    result: "नया नतीजा",
    newScore: "नया स्कोर",
    change: "बदलाव",
    pts: "अंक",
    pt: "अंक",
    decision: "फ़ैसला",
    approved: "स्वीकृत",
    declined: "अस्वीकृत",
    toApproval: "स्वीकृति तक अंक",
    reached: "पहुँच गए",
    apr: "सालाना दर",
    noApr: "कोई प्राइम ऑफ़र नहीं",
    emi: "मासिक EMI",
    interestSaved: "ब्याज की बचत",
    noSaving: "अभी कोई बचत नहीं",
    loanNote: "{amount} पर {term} महीने के लिए। दरें उदाहरण के लिए हैं।",
    reset: "रीसेट",
    apply: "ये आँकड़े इस्तेमाल करें",
  },
};

const mr: Strings = {
  hero: {
    kicker: "तुमचे उत्तर",
    declinedAt: "तुम्ही {score} वर आहात.",
    approvedAt: "तुम्ही {score} वर मंजूर आहात.",
    away: "मंजुरीपासून {n} गुण दूर.",
    aboutRange: "सुमारे {when}, बहुधा {low} ते {high} महिने.",
    about: "सुमारे {when}.",
    noPlan: "आमच्या मॉडेलमधील कोणत्याही योजनेने {n} महिन्यांत मंजुरी मिळत नाही.",
    nextTier: "पुढील दर स्तर {n} गुण दूर आहे.",
    bestTier: "तुम्ही आधीच सर्वोत्तम दर स्तरात आहात.",
    foot: "स्कोअर आणि वेळ क्रेडिट मॉडेल आणि तुमच्या योजनेच्या सिम्युलेशनमधून येतात.",
  },
  breakdown: {
    kicker: "स्कोअरच्या आत",
    title: "काय स्कोअर वाढवते आणि काय कमी करते",
    sub: "मॉडेल वाचत असलेली प्रत्येक माहिती, सरासरी अर्जदाराच्या तुलनेत गुणांमध्ये.",
    lifts: "स्कोअर वाढवते",
    pulls: "स्कोअर कमी करते",
    pts: "गुण",
    nothingLifts: "सध्या काहीही स्कोअरला सरासरीच्या वर नेत नाही.",
    nothingPulls: "काहीही स्कोअरला सरासरीच्या खाली ओढत नाही.",
    note: "गुण हे मॉडेलचे अचूक योगदान आहेत, अंदाज नाहीत.",
  },
  whatIf: {
    kicker: "असे झाले तर",
    title: "बदल करून पाहा आणि स्कोअर हलताना पाहा",
    sub: "स्लायडर हलवा. तेच मॉडेल नवीन आकड्यांना लगेच स्कोअर करते. काहीही जतन होत नाही.",
    sliders: "तुमचे आकडे",
    utilization: "कार्ड वापर",
    debtRatio: "कर्ज गुणोत्तर (उत्पन्नाच्या तुलनेत EMI)",
    incomeGrowth: "उत्पन्नात वाढ",
    openCreditLines: "चालू कर्जे आणि कार्ड",
    monthsWaited: "वेळेवर भरलेले महिने",
    today: "आज: {value}",
    incomeUnusable: "उत्पन्न दिलेले नाही, त्यामुळे वाढीने स्कोअर बदलणार नाही.",
    monthsHint: "24 महिन्यांपेक्षा जुने उशिराचे हप्ते वगळले जातात.",
    result: "नवा निकाल",
    newScore: "नवा स्कोअर",
    change: "बदल",
    pts: "गुण",
    pt: "गुण",
    decision: "निर्णय",
    approved: "मंजूर",
    declined: "नामंजूर",
    toApproval: "मंजुरीसाठी गुण",
    reached: "गाठले",
    apr: "वार्षिक दर",
    noApr: "प्राइम ऑफर नाही",
    emi: "मासिक EMI",
    interestSaved: "व्याजाची बचत",
    noSaving: "अजून बचत नाही",
    loanNote: "{amount} वर {term} महिन्यांसाठी. दर उदाहरणादाखल आहेत.",
    reset: "रीसेट",
    apply: "हे आकडे वापरा",
  },
};

const STRINGS: Record<Lang, Strings> = { en, hi, mr };

export type WhatIfStrings = Strings;
export const whatIfStrings = (lang: Lang): Strings => STRINGS[lang];
