/**
 * Writes supabase/migrations/20261007000001_seed_government_schemes.sql from the controlled seed
 * file supabase/seed/government_schemes.json.
 *
 *   npm run seed:schemes
 *
 * Every entry is validated with `schemeSeedSchema` first; on a problem nothing is written and the
 * process exits non-zero with a readable message. The SQL is idempotent: an entry whose
 * (slug, version) already exists is skipped, so the migration can be run again safely, and a
 * changed scheme is added as a new version in the seed file rather than by editing version 1.
 *
 * The seed file is the only place real scheme data lives in the repository; the app reads schemes
 * from the database and never imports this file.
 */
import fs from "node:fs";
import path from "node:path";
import { schemeSeedSchema, type SchemeSeed } from "../lib/schemes/schema";

const root = path.resolve(__dirname, "..");
export const SEED_PATH = path.join(root, "supabase/seed/government_schemes.json");
export const OUTPUT_PATH = path.join(root, "supabase/migrations/20261007000001_seed_government_schemes.sql");

/**
 * A Postgres dollar-quoted string literal. The tag is chosen so that no "$tag" occurs anywhere in
 * the value, so nothing in the value can end the literal early (not a quote, not "$$").
 */
export function sqlText(value: string): string {
  let tag = "seed";
  for (let n = 1; value.includes(`$${tag}`); n++) tag = `seed${n}`;
  return `$${tag}$${value}$${tag}$`;
}

/** A number as a SQL literal, or null. Seed numbers are validated finite by the schema. */
function sqlNumeric(value: number | null): string {
  if (value === null) return "null::numeric";
  if (!Number.isFinite(value)) throw new Error(`cannot write ${value} as a number`);
  return `${value}::numeric`;
}

const sqlJson = (value: unknown, space?: number) => `${sqlText(JSON.stringify(value, null, space))}::jsonb`;
const sqlDate = (value: string | null) => (value === null ? "null::date" : `${sqlText(value)}::date`);

function insertFor(e: SchemeSeed): string {
  // Plain literals in an INSERT ... SELECT would be typed as text, so every non-text column is cast.
  // The guard is a "where not exists" and not "on conflict do nothing": the versioning trigger
  // runs before the conflict check and would raise for a version that is already there.
  return [
    `insert into public.government_schemes (`,
    `  slug, version, is_current, status, name, short_name, scheme_type, summary, benefits,`,
    `  implementing_agency, ministry, min_loan_amount, max_loan_amount, eligibility_rules,`,
    `  how_to_apply, application_url, official_url, sources, last_verified_at, verification_status,`,
    `  effective_from`,
    `)`,
    `select`,
    `  ${sqlText(e.slug)},`,
    `  ${Math.trunc(e.version)}::integer,`,
    `  true,`,
    `  ${sqlText(e.status)},`,
    `  ${sqlText(e.name)},`,
    `  ${sqlText(e.short_name)},`,
    `  ${sqlText(e.scheme_type)},`,
    `  ${sqlText(e.summary)},`,
    `  ${sqlJson(e.benefits)},`,
    `  ${sqlText(e.implementing_agency)},`,
    `  ${e.ministry === null ? "null::text" : sqlText(e.ministry)},`,
    `  ${sqlNumeric(e.min_loan_amount)},`,
    `  ${sqlNumeric(e.max_loan_amount)},`,
    `  ${sqlJson(e.eligibility_rules, 2)},`,
    `  ${e.how_to_apply === null ? "null::text" : sqlText(e.how_to_apply)},`,
    `  ${e.application_url === null ? "null::text" : sqlText(e.application_url)},`,
    `  ${sqlText(e.official_url)},`,
    `  ${sqlJson(e.sources)},`,
    `  ${sqlDate(e.last_verified_at)},`,
    `  ${sqlText(e.verification_status)},`,
    `  ${sqlDate(e.effective_from)}`,
    `where not exists (`,
    `  select 1 from public.government_schemes where slug = ${sqlText(e.slug)} and version = ${Math.trunc(e.version)}`,
    `);`,
  ].join("\n");
}

/** The whole seed migration for these (already validated) entries. Pure: same input, same text. */
export function seedSql(entries: SchemeSeed[]): string {
  const header = [
    "-- GENERATED FILE. Do not edit by hand.",
    "-- Generated by scripts/seed-schemes.ts from supabase/seed/government_schemes.json;",
    "-- change the JSON and run `npm run seed:schemes` to regenerate this file.",
    "--",
    "-- Loads the reviewed starting data for public.government_schemes. Run it after",
    "-- 20261007000000_government_schemes.sql. It is safe to run again: an entry whose (slug, version)",
    "-- already exists is skipped. Each entry carries its official source URLs and the date it was",
    "-- last checked against them (last_verified_at); an entry that could not be fully checked is",
    "-- marked verification_status = 'unverified'.",
    "",
  ].join("\n");
  // The label is a SQL comment, so it must stay on one line whatever the name contains.
  const oneLine = (s: string) => s.replace(/\s+/g, " ").trim();
  const body = entries.map((e) => `-- ${oneLine(`${e.name} (${e.slug}, version ${e.version})`)}\n${insertFor(e)}`).join("\n\n");
  return `${header}\n${body}\n`;
}

/** Reads and validates the seed file. Throws an Error whose message lists every problem. */
export function loadSeed(file = SEED_PATH): SchemeSeed[] {
  let raw: unknown;
  try {
    raw = JSON.parse(fs.readFileSync(file, "utf8"));
  } catch (err) {
    throw new Error(`Cannot read ${path.relative(root, file)}: ${err instanceof Error ? err.message : String(err)}`);
  }
  if (!Array.isArray(raw)) throw new Error(`${path.relative(root, file)} must contain a JSON array of schemes.`);

  const problems: string[] = [];
  const entries: SchemeSeed[] = [];
  raw.forEach((item, i) => {
    const parsed = schemeSeedSchema.safeParse(item);
    const label = `entry ${i + 1} (${typeof item?.slug === "string" ? item.slug : "no slug"})`;
    if (parsed.success) entries.push(parsed.data);
    else for (const issue of parsed.error.issues) problems.push(`${label}: ${issue.path.join(".") || "(entry)"}: ${issue.message}`);
  });

  const seen = new Set<string>();
  for (const e of entries) {
    const key = `${e.slug}@${e.version}`;
    if (seen.has(key)) problems.push(`${key} appears twice`);
    seen.add(key);
  }
  if (problems.length > 0) throw new Error(`The seed file is not valid:\n  ${problems.join("\n  ")}`);
  return entries;
}

function main() {
  try {
    const entries = loadSeed();
    fs.writeFileSync(OUTPUT_PATH, seedSql(entries), "utf8");
    console.log(`Wrote ${entries.length} scheme(s) to ${path.relative(root, OUTPUT_PATH)}`);
  } catch (err) {
    console.error(err instanceof Error ? err.message : String(err));
    process.exit(1);
  }
}

// Only write the file when this is run as a script (npm run seed:schemes), never when imported.
if (/seed-schemes\.[cm]?[jt]s$/.test(process.argv[1] ?? "")) main();
